# Generated by Django 3.1.3 on 2020-11-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_category_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_items')),
                ('review', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_approved_by', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_brand', to='core.brand')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_category', to='core.category')),
                ('creat_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_sub_category', to='core.category')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ItemsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(upload_to='item_file')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_files', to='review.item')),
            ],
            options={
                'db_table': 'item_files',
            },
        ),
    ]
