# Generated by Django 3.1.3 on 2020-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20201128_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
