# Generated by Django 3.1.3 on 2020-11-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
    ]
