# Generated by Django 3.1.3 on 2020-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201123_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
