# Generated by Django 3.1.3 on 2020-11-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0003_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='The name of the content from which this unit of history is generated', max_length=255, null=True, verbose_name='Name of Content')),
                ('description', models.CharField(blank=True, help_text='From where this unit of history is generated', max_length=255, null=True, verbose_name='Description of Content')),
                ('user', models.CharField(blank=True, help_text='for which User', max_length=255, null=True, verbose_name='User name')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
